quarkus.langchain4j.mcp.service-account-name.transport-type=streamable-http
quarkus.langchain4j.mcp.service-account-name.url=http://localhost:8080/mcp

quarkus.oidc-client.auth-server-url=http://localhost:9080/realms/quarkus
quarkus.oidc-client.client-id=quarkus-mcp-client
quarkus.oidc-client.credentials.secret=${QUARKUS_MCP_CLIENT_SECRET}
quarkus.oidc-client.scopes=quarkus-mcp-server-scope

quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-mini
quarkus.langchain4j.openai.chat-model.log-requests=true
quarkus.langchain4j.openai.chat-model.log-responses=true
quarkus.langchain4j.openai.chat-model.temperature=1.0
quarkus.langchain4j.openai.chat-model.max-completion-tokens=1000
quarkus.langchain4j.openai.chat-model.frequency-penalty=0


quarkus.http.port=8085


# quarkus.log.category."io.quarkus.oidc-client".level=DEBUG