
quarkus.http.port=8087

# Default Quarkus OIDC tenant verifies access tokens which reach the MCP server.
# Default OIDC tenant properties such as the Keycloak address are set in devmode by the Keycloak Dev Service. 
quarkus.oidc.client-id=quarkus-mcp-server
# All tokens verified by this default OIDC tenant must target only this MCP server,
# with the token audience (`aud`) claim containing `quarkus-mcp-server`
quarkus.oidc.token.audience=quarkus-mcp-server

quarkus.oidc.auth-server-url=http://localhost:9080/realms/quarkus

# Keycloak devservice that enables a default OIDC tenant that secures MCP server 
# Keycloak may require more memory on some systems
quarkus.devservices.enabled=false

# MCP server tool uses REST Client to access a protected REST server to complete a service account name request.
# REST server expects tokens that contain a `quarkus-mcp-service` audience to prove they are intended for the REST server only.
# Therefore, instead of propagating the token whose audience is this MCP `quarkus-mcp-server` server,
# the token is exchanged to create a new token with the correct target audience set to `quarkus-mcp-service`.


# OIDC `service-account-name-rest-server` tenant that secures a protected REST server.
# It enforces that all tokens that reach it have a `quarkus-mcp-service` audience.
quarkus.oidc.service-account-name-rest-server.auth-server-url=http://localhost:9080/realms/quarkus
quarkus.oidc.service-account-name-rest-server.token.audience=quarkus-mcp-service
quarkus.oidc.service-account-name-rest-server.tenant-paths=/service-account-name

